eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
 # instance:
 #   hostname: localhost
server:
  port: 5020
spring:
  application:
    name: customer-service   
  cloud:
    config:
      discovery:
        enabled: true
      name: customer
      profile: development
      label: develop   