eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
 # instance:
   # hostname: localhost
server:
  port: 5030
spring:
  application:
    name: employee-service   